export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const FETCH_PRODUCTS_BY_SELLER = 'FETCH_PRODUCTS_BY_SELLER';

export const CREATE_SELLER = 'CREATE_SELLER';
export const FETCH_SELLERS = 'FETCH_SELLERS';
export const FETCH_SELLER = 'FETCH_SELLER';
export const DELETE_SELLER = 'DELETE_SELLER';
export const EDIT_SELLER = 'EDIT_SELLER';
