import React, { Component } from "react";
import { Card, Grid, Icon, Image } from "semantic-ui-react";
import "./ImageGrid.css";

export default class ImageGrid extends Component {
  render() {
    return (
      <div className="ui container image-wrapper">
        <h1 style={{ textAlign: "center" }}>Trending</h1>
        <Grid centered>
          <Grid.Column mobile={16} tablet={8} computer={4}>
            <Card>
              <Image
                src="https://cdn.notonthehighstreet.com/fs/40/a2/fdb3-678a-41d4-9d4d-8f5a315c0ac5/original_red-and-blue-abstract-paintings-on-cotton-canvas-set.jpg"
                size="medium"
                wrapped
                ui={false}
              />
              <Icon
                className="icon-image-left"
                size="large"
                name="heart"
                circular
                inverted
                color="green"
              />
              <Icon
                className="icon-image-right"
                size="large"
                name="cart"
                circular
                inverted
                color="blue"
              />
            </Card>
          </Grid.Column>
          <Grid.Column mobile={16} tablet={8} computer={4}>
            <Card>
              <Image
                src="https://cdn.notonthehighstreet.com/fs/40/a2/fdb3-678a-41d4-9d4d-8f5a315c0ac5/original_red-and-blue-abstract-paintings-on-cotton-canvas-set.jpg"
                size="medium"
                wrapped
                ui={false}
              />
              <Icon
                className="icon-image-left"
                size="large"
                name="heart"
                circular
                inverted
                color="green"
              />
              <Icon
                className="icon-image-right"
                size="large"
                name="cart"
                circular
                inverted
                color="blue"
              />
            </Card>
          </Grid.Column>
          <Grid.Column mobile={16} tablet={8} computer={4}>
            <Card>
              <Image
                src="https://cdn.notonthehighstreet.com/fs/40/a2/fdb3-678a-41d4-9d4d-8f5a315c0ac5/original_red-and-blue-abstract-paintings-on-cotton-canvas-set.jpg"
                size="medium"
                wrapped
                ui={false}
              />
              <Icon
                className="icon-image-left"
                size="large"
                name="heart"
                circular
                inverted
                color="green"
              />
              <Icon
                className="icon-image-right"
                size="large"
                name="cart"
                circular
                inverted
                color="blue"
              />
            </Card>
          </Grid.Column>
          <Grid.Column mobile={16} tablet={8} computer={4}>
            <Card>
              <Image
                src="https://cdn.notonthehighstreet.com/fs/40/a2/fdb3-678a-41d4-9d4d-8f5a315c0ac5/original_red-and-blue-abstract-paintings-on-cotton-canvas-set.jpg"
                size="medium"
                wrapped
                ui={false}
              />
              <Icon
                className="icon-image-left"
                size="large"
                name="heart"
                circular
                inverted
                color="green"
              />
              <Icon
                className="icon-image-right"
                size="large"
                name="cart"
                circular
                inverted
                color="blue"
              />
            </Card>
          </Grid.Column>
          <Grid.Column mobile={16} tablet={8} computer={4}>
            <Card>
              <Image
                src="https://cdn.notonthehighstreet.com/fs/40/a2/fdb3-678a-41d4-9d4d-8f5a315c0ac5/original_red-and-blue-abstract-paintings-on-cotton-canvas-set.jpg"
                size="medium"
                wrapped
                ui={false}
              />
              <Icon
                className="icon-image-left"
                size="large"
                name="heart"
                circular
                inverted
                color="green"
              />
              <Icon
                className="icon-image-right"
                size="large"
                name="cart"
                circular
                inverted
                color="blue"
              />
            </Card>
          </Grid.Column>
          <Grid.Column mobile={16} tablet={8} computer={4}>
            <Card>
              <Image
                src="https://cdn.notonthehighstreet.com/fs/40/a2/fdb3-678a-41d4-9d4d-8f5a315c0ac5/original_red-and-blue-abstract-paintings-on-cotton-canvas-set.jpg"
                size="medium"
                wrapped
                ui={false}
              />
              <Icon
                className="icon-image-left"
                size="large"
                name="heart"
                circular
                inverted
                color="green"
              />
              <Icon
                className="icon-image-right"
                size="large"
                name="cart"
                circular
                inverted
                color="blue"
              />
            </Card>
          </Grid.Column>
          <Grid.Column mobile={16} tablet={8} computer={4}>
            <Card>
              <Image
                src="https://cdn.notonthehighstreet.com/fs/40/a2/fdb3-678a-41d4-9d4d-8f5a315c0ac5/original_red-and-blue-abstract-paintings-on-cotton-canvas-set.jpg"
                size="medium"
                wrapped
                ui={false}
              />
              <Icon
                className="icon-image-left"
                size="large"
                name="heart"
                circular
                inverted
                color="green"
              />
              <Icon
                className="icon-image-right"
                size="large"
                name="cart"
                circular
                inverted
                color="blue"
              />
            </Card>
          </Grid.Column>
          <Grid.Column mobile={16} tablet={8} computer={4}>
            <Card>
              <Image
                src="https://cdn.notonthehighstreet.com/fs/40/a2/fdb3-678a-41d4-9d4d-8f5a315c0ac5/original_red-and-blue-abstract-paintings-on-cotton-canvas-set.jpg"
                size="medium"
                wrapped
                ui={false}
              />
              <Icon
                className="icon-image-left"
                size="large"
                name="heart"
                circular
                inverted
                color="green"
              />
              <Icon
                className="icon-image-right"
                size="large"
                name="cart"
                circular
                inverted
                color="blue"
              />
            </Card>
          </Grid.Column>
        </Grid>
      </div>
    );
  }
}